apiVersion: v1
kind: Pod
metadata:
  name: uptimed
  labels:
    name: uptimed
spec:
  securityContext:
    runAsUser: 1
  initContainers:
  - name: init-uptimed
    image: bash
    command: ["bash", "-c"]
    args: ["sleep 5"]
  containers:
  - name: uptimed
    image: uptimed
    ports:
    - containerPort: 2222
  - name: while
    image: bash
    command: ["bash", "-c"]
    args: ["while true; do cat /etc/uptimed/test.txt; sleep 1; done"]
    volumeMounts:
    - mountPath: /data/cdrom
      name: demo-volume
    - mountPath: /etc/uptimed
      name: uptimed-conf-volume
  volumes:
  - name: demo-volume
    emptyDir: {}
  - name: uptimed-conf-volume
    configMap:
      defaultMode: 420
      name: uptimed-conf
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: uptimed-conf
data:
  test.txt: |-
    hello
