name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2


    - name: Check formatting
      run: go fmt

    - name: Vet
      run: go vet

    - name: systemk Build
      run: go build -v ./...

    - name: systemk Test (unit)
      run: go test -v ./...
